M48
; DRILL file {KiCad 9.0.2} date 2025-05-19T10:19:58-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-19T10:19:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X94.0Y-84.735
X94.0Y-129.875
X190.02Y-84.735
X190.02Y-129.875
T2
X179.2Y-98.995
M30
